### ISSUE TITLE
Consider using "used_within_repositories" to find orphan objects

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/ArchivesSnake#10]
The `used_within_repositories` key may be a better way to find orphaned objects than the current implementation of `get_orphans`. However, we need to make sure that this key is present in all objects which may be orphaned.

To do:
- Review all objects which can be orphaned and determine whether or not they have the `used_within_repositories` key
- Consider whether or not it makes sense to target this key rather than the more generic approach currently taken

**Comment by a-berish** [comment]
The `used_within_repositories` key is not present in top container JSON. In order to find out if a top container is orphaned, you might look at whether or not it is linked to a collection by looking at the `collection` key inside the top container JSON. Because this is not much different than what the get_orphans function already does, I do not think it makes sense to change our approach.
